"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { motion, AnimatePresence } from "framer-motion";
import { Heart, Sparkles, User, Copy, Check, ArrowRight, LogOut } from "lucide-react";
import { toast } from "sonner";
import Image from "next/image";

type PairingStep = "profile" | "session_choice" | "create_display" | "join_input";

export default function PairingPage() {
  const router = useRouter();
  const supabase = createClient();
  const [user, setUser] = useState<any>(null);
  
  // Form State
  const [displayName, setDisplayName] = useState("");
  const [role, setRole] = useState<"task_user" | "reward_giver">("task_user");
  const [step, setStep] = useState<PairingStep>("profile");
  
  // Code State
  const [enteredCode, setEnteredCode] = useState("");
  const [createdCode, setCreatedCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [appUrl, setAppUrl] = useState("");

  useEffect(() => {
    if (typeof window !== "undefined") {
      setAppUrl(window.location.origin);
    }
  }, []);

  useEffect(() => {
    async function checkUser() {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push("/login");
        return;
      }
      setUser(user);

      // Check if user already has a profile row (created during login)
      const { data: profileData } = await (supabase
        .from("users") as any)
        .select("*")
        .eq("id", user.id)
        .single();

      const profile = profileData as any;

      // Extract invite code if passed in URL
      const params = new URLSearchParams(window.location.search);
      const codeParam = params.get("code");
      if (codeParam) {
        setEnteredCode(codeParam.toUpperCase());
      }

      if (profile?.couple_session_id) {
        router.push("/dashboard");
        return;
      }

      if (profile?.display_name) {
        // Username was set at login — skip straight to session choice
        setDisplayName(profile.display_name);
        setRole(profile.role || "task_user");
        if (codeParam) {
          setStep("join_input");
        } else {
          setStep("session_choice");
        }
      } else {
        // Fallback: show profile step so they can set a name
        setStep("profile");
      }
    }
    checkUser();
  }, [router, supabase]);

  const handleCreateProfile = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!displayName.trim()) {
      toast.error("Please enter a display name");
      return;
    }
    
    // If there is an invite code in state, skip session choice and go to join input
    if (enteredCode) {
      setStep("join_input");
    } else {
      setStep("session_choice");
    }
  };


  const handleCreateSession = async () => {
    setLoading(true);
    try {
      // 1. Insert new couple session (invite code is generated by default)
      const { data: sessionData, error: sessionError } = await (supabase
        .from("couple_sessions") as any)
        .insert([{}]) // Empty insert trigger default code generation
        .select()
        .single();

      if (sessionError) throw sessionError;

      // 2. Insert or update user profile with role and session ID
      const { error: userError } = await (supabase
        .from("users") as any)
        .upsert({
          id: user.id,
          display_name: displayName.trim(),
          role: role,
          couple_session_id: sessionData.id,
        });

      if (userError) throw userError;

      // 3. Clone template rewards for this session
      const { data: templates } = await (supabase
        .from("rewards") as any)
        .select("*")
        .is("couple_session_id", null);

      if (templates && templates.length > 0) {
        const clonedTemplates = templates.map((r: any) => ({
          couple_session_id: sessionData.id,
          title: r.title,
          description: r.description,
          category: r.category,
          cost: r.cost,
          reward_type: r.reward_type,
          icon: r.icon,
          cooldown_hours: r.cooldown_hours,
          hidden: r.hidden,
          active: r.active,
          sort_order: r.sort_order,
          created_by: user.id,
        }));

        const { error: cloneError } = await (supabase
          .from("rewards") as any)
          .insert(clonedTemplates);

        if (cloneError) console.error("Template cloning failed:", cloneError);
      }

      setCreatedCode(sessionData.invite_code);
      setStep("create_display");
      toast.success("Relationship session created!");
    } catch (err: any) {
      toast.error(err.message || "Failed to create session");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleJoinSession = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!enteredCode.trim()) {
      toast.error("Please enter an invite code");
      return;
    }

    setLoading(true);
    try {
      const cleanCode = enteredCode.trim().toUpperCase();

      // 1. Look up session by invite code
      const { data: session, error: sessionError } = await (supabase
        .from("couple_sessions") as any)
        .select("*")
        .eq("invite_code", cleanCode)
        .single();

      if (sessionError || !session) {
        toast.error("Invalid invite code. Ask your partner for their code!");
        setLoading(false);
        return;
      }

      // 2. Create or update user profile with role and session ID
      const { error: userError } = await (supabase
        .from("users") as any)
        .upsert({
          id: user.id,
          display_name: displayName.trim(),
          role: role,
          couple_session_id: session.id,
        });

      if (userError) throw userError;

      toast.success("Successfully paired with your partner! ❤️");
      router.push("/dashboard");
    } catch (err: any) {
      toast.error(err.message || "Failed to join session");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(createdCode);
    setCopied(true);
    toast.success("Code copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const copyShareLink = () => {
    navigator.clipboard.writeText(`${appUrl}/pairing?code=${createdCode}`);
    setShareCopied(true);
    toast.success("Pairing link copied to clipboard!");
    setTimeout(() => setShareCopied(false), 2000);
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();
    router.push("/login");
  };

  return (
    <main className="min-h-screen w-screen bg-dark flex items-center justify-center p-4 relative overflow-hidden select-none">
      {/* Background Gradients */}
      <div className="absolute inset-0 bg-gradient-glow pointer-events-none opacity-40" />
      <div className="absolute -top-40 -left-40 w-96 h-96 rounded-full bg-primary/10 blur-[128px] pointer-events-none" />
      <div className="absolute -bottom-40 -right-40 w-96 h-96 rounded-full bg-accent/10 blur-[128px] pointer-events-none" />

      {/* Logout button at top right */}
      <button
        onClick={handleLogout}
        className="absolute top-4 right-4 flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/[0.03] border border-white/[0.08] text-xs font-heading font-medium text-white/60 hover:text-white hover:bg-white/[0.06] transition-all duration-200 cursor-pointer"
      >
        <LogOut className="w-3.5 h-3.5" />
        Logout
      </button>

      <AnimatePresence mode="wait">
        {step === "profile" && (
          <motion.div
            key="profile"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="w-full max-w-md card-glass border border-white/[0.08] shadow-2xl p-8"
          >
            <div className="flex flex-col items-center mb-6">
              <Sparkles className="w-8 h-8 text-primary animate-pulse mb-3" />
              <h1 className="text-2xl font-heading font-bold text-white text-center">Create Your Profile</h1>
              <p className="text-xs font-body text-white/50 text-center mt-1">
                Tell us your name and role in the relationship.
              </p>
            </div>

            <form onSubmit={handleCreateProfile} className="space-y-6">
              <div className="space-y-1">
                <label className="text-xs font-heading font-semibold uppercase tracking-wider text-white/60">
                  Your Display Name
                </label>
                <div className="relative flex items-center">
                  <User className="absolute left-4 w-4 h-4 text-white/40" />
                  <input
                    type="text"
                    value={displayName}
                    onChange={(e) => setDisplayName(e.target.value)}
                    placeholder="Enter your first name or nickname..."
                    className="input pl-11 text-white bg-white/[0.03] border-white/[0.08] focus:border-primary"
                    required
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-heading font-semibold uppercase tracking-wider text-white/60">
                  Choose Your Role
                </label>
                <div className="grid grid-cols-2 gap-4">
                  {/* Task User Option */}
                  <div
                    onClick={() => setRole("task_user")}
                    className={`cursor-pointer rounded-2xl p-4 border flex flex-col items-center gap-2 transition-all duration-200 ${
                      role === "task_user"
                        ? "bg-primary/10 border-primary shadow-glow-primary-sm"
                        : "bg-white/[0.02] border-white/[0.08] hover:border-white/20"
                    }`}
                  >
                    <Heart className={`w-6 h-6 ${role === "task_user" ? "fill-primary text-primary" : "text-white/40"}`} />
                    <span className="font-heading font-bold text-xs">Task User</span>
                    <span className="text-[10px] text-white/50 text-center font-body leading-tight">
                      I will log daily tasks & earn streak milestones.
                    </span>
                  </div>

                  {/* Reward Giver Option */}
                  <div
                    onClick={() => setRole("reward_giver")}
                    className={`cursor-pointer rounded-2xl p-4 border flex flex-col items-center gap-2 transition-all duration-200 ${
                      role === "reward_giver"
                        ? "bg-primary/10 border-primary shadow-glow-primary-sm"
                        : "bg-white/[0.02] border-white/[0.08] hover:border-white/20"
                    }`}
                  >
                    <Sparkles className={`w-6 h-6 ${role === "reward_giver" ? "text-primary fill-primary/10" : "text-white/40"}`} />
                    <span className="font-heading font-bold text-xs">Reward Giver</span>
                    <span className="text-[10px] text-white/50 text-center font-body leading-tight">
                      I will approve redemptions & manage rewards.
                    </span>
                  </div>
                </div>
              </div>

              <button
                type="submit"
                className="w-full btn-primary py-3.5 flex items-center justify-center gap-2 font-bold text-sm"
              >
                Continue
                <ArrowRight className="w-4 h-4" />
              </button>
            </form>
          </motion.div>
        )}

        {step === "session_choice" && (
          <motion.div
            key="session_choice"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="w-full max-w-md card-glass border border-white/[0.08] shadow-2xl p-8 text-center"
          >
            <div className="flex flex-col items-center mb-6">
              <Heart className="w-8 h-8 text-primary fill-primary/20 animate-pulse mb-3" />
              <h1 className="text-2xl font-heading font-bold text-white">Connect with Partner</h1>
              <p className="text-xs font-body text-white/50 mt-1 max-w-[280px]">
                Create a new cozy relationship workspace, or enter your partner's invite code to join theirs.
              </p>
            </div>

            <div className="flex flex-col gap-4 mt-6">
              {/* Option A: Create a Session */}
              <button
                onClick={handleCreateSession}
                disabled={loading}
                className="w-full btn-primary py-4 flex flex-col items-center gap-1 cursor-pointer font-bold text-sm"
              >
                <span>Create a New Space</span>
                <span className="text-[10px] text-white/80 font-normal font-body">Generates a code for your partner</span>
              </button>

              <div className="relative my-2 flex items-center justify-center">
                <div className="absolute inset-0 flex items-center"><div className="w-full border-t border-white/[0.08]" /></div>
                <span className="relative px-3 bg-[#1e1e1e]/90 text-[10px] font-heading font-bold text-white/40 uppercase tracking-widest">Or</span>
              </div>

              {/* Option B: Join a Session */}
              <button
                onClick={() => setStep("join_input")}
                className="w-full btn-ghost py-4 flex flex-col items-center gap-1 cursor-pointer font-bold text-sm"
              >
                <span>Join an Existing Space</span>
                <span className="text-[10px] text-white/40 font-normal font-body">Enter code from your partner</span>
              </button>

              <button
                onClick={() => setStep("profile")}
                className="text-xs text-white/40 font-heading font-medium hover:text-white hover:underline mt-4 cursor-pointer"
              >
                ← Back to Profile Setup
              </button>
            </div>
          </motion.div>
        )}

        {step === "create_display" && (
          <motion.div
            key="create_display"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="w-full max-w-md card-glass border border-white/[0.08] shadow-2xl p-8 text-center flex flex-col items-center"
          >
            <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center border border-primary/20 text-primary mb-4">
              <Sparkles className="w-6 h-6 fill-primary/10 animate-bounce" />
            </div>

            <h1 className="text-2xl font-heading font-bold text-white">Your Invite Code</h1>
            <p className="text-xs font-body text-white/50 mt-1 max-w-[280px]">
              Share this secret code with your partner. They must enter it on their pairing screen to connect with you.
            </p>

            {/* Code display widget */}
            <div className="w-full mt-6 p-4 rounded-2xl bg-white/[0.03] border border-white/[0.08] flex items-center justify-between gap-4">
              <span className="font-mono text-2xl font-bold tracking-widest text-primary pl-2">
                {createdCode}
              </span>
              <button
                onClick={copyToClipboard}
                className="btn-ghost px-4 py-2.5 flex items-center gap-1.5 text-xs text-white/80 cursor-pointer"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-green-400" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    Copy Code
                  </>
                )}
              </button>
            </div>

            {/* Premium Share Options */}
            <div className="w-full mt-3 flex flex-col gap-2">
              <button
                onClick={copyShareLink}
                className="w-full btn-ghost py-3 flex items-center justify-center gap-2 text-xs font-semibold text-white/80 cursor-pointer"
              >
                {shareCopied ? (
                  <>
                    <Check className="w-4 h-4 text-green-400" />
                    Link Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy Pairing Link
                  </>
                )}
              </button>
              
              <a
                href={`https://api.whatsapp.com/send?text=${encodeURIComponent(
                  `Join my private BondXP space! ❤️\n\nClick here to pair with me instantly:\n${appUrl}/pairing?code=${createdCode}\n\n(Or enter invite code: ${createdCode})`
                )}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-full bg-[#25D366] hover:bg-[#20ba5a] text-black font-heading font-bold text-xs rounded-xl py-3 flex items-center justify-center gap-2 transition-all duration-200 cursor-pointer no-underline"
              >
                <svg className="w-4 h-4 fill-current" viewBox="0 0 24 24">
                  <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.513 2.262 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.724-1.457L0 24zm6.59-4.846c1.6.95 3.188 1.449 4.825 1.451 5.436 0 9.86-4.42 9.864-9.864.002-2.637-1.03-5.114-2.905-6.989-1.873-1.873-4.354-2.904-6.993-2.906-5.44 0-9.867 4.42-9.871 9.863 0 1.764.462 3.486 1.341 5.021l-.97 3.548 3.634-.954zm10.985-7.353c-.304-.153-1.8-.886-2.077-.988-.278-.102-.48-.153-.68.153-.2.304-.778.988-.953 1.19-.177.2-.353.228-.657.076-.304-.153-1.285-.473-2.448-1.51-1.01-.902-1.604-2.016-1.802-2.355-.198-.34-.02-.523.15-.693.153-.153.304-.353.457-.529.153-.177.203-.304.304-.508.102-.2.05-.381-.026-.533-.076-.153-.68-1.637-.932-2.247-.246-.593-.496-.51-.68-.52-.177-.01-.38-.01-.58-.01-.2 0-.529.076-.807.38-.278.304-1.062 1.039-1.062 2.535 0 1.497 1.088 2.943 1.24 3.146.153.2 2.142 3.272 5.19 4.587.724.312 1.29.499 1.73.639.728.23 1.39.196 1.91.119.58-.087 1.8-.737 2.053-1.448.253-.71.253-1.32.177-1.448-.076-.127-.278-.203-.581-.355z"/>
                </svg>
                Share via WhatsApp
              </a>
            </div>

            <button
              onClick={() => router.push("/dashboard")}
              className="w-full btn-primary py-3.5 mt-8 font-bold text-sm"
            >
              Enter Dashboard
            </button>
          </motion.div>
        )}

        {step === "join_input" && (
          <motion.div
            key="join_input"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="w-full max-w-md card-glass border border-white/[0.08] shadow-2xl p-8"
          >
            <div className="flex flex-col items-center mb-6">
              <Heart className="w-8 h-8 text-primary fill-primary/20 animate-pulse mb-3" />
              <h1 className="text-2xl font-heading font-bold text-white text-center">Join Partner's Space</h1>
              <p className="text-xs font-body text-white/50 text-center mt-1">
                Enter the secret 8-character invite code generated by your partner.
              </p>
            </div>

            <form onSubmit={handleJoinSession} className="space-y-6">
              <div className="space-y-1">
                <label className="text-xs font-heading font-semibold uppercase tracking-wider text-white/60">
                  Invite Code
                </label>
                <input
                  type="text"
                  value={enteredCode}
                  onChange={(e) => setEnteredCode(e.target.value)}
                  placeholder="e.g. A1B2C3D4"
                  maxLength={8}
                  disabled={loading}
                  className="input text-center text-lg font-mono tracking-widest text-primary uppercase bg-white/[0.03] border-white/[0.08] focus:border-primary"
                  required
                />
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full btn-primary py-3.5 flex items-center justify-center gap-2 font-bold text-sm"
              >
                {loading ? "Connecting..." : "Pair & Start"}
                {!loading && <ArrowRight className="w-4 h-4" />}
              </button>

              <div className="flex justify-center">
                <button
                  type="button"
                  onClick={() => setStep("session_choice")}
                  className="text-xs text-white/40 font-heading font-medium hover:text-white hover:underline cursor-pointer"
                >
                  ← Back to Options
                </button>
              </div>
            </form>
          </motion.div>
        )}
      </AnimatePresence>
    </main>
  );
}
